### ISSUE TITLE
Multi-monitors background scale

### ISSUE THREAD

**Issue by lonble** [realmazharhussain/gdm-tools#1]
On multi-monitors, the background image will be stretched to all screens, which will cause the background image to be blurred and the scale is inappropriate. Can the background image be displayed separately on each monitor?

**I love this tool very much!**

**Comment by realmazharhussain** [comment]
I'm really sorry for being so much late to reply.

Actually, background image/color is part of gnome-shell theme that can be compiled and applied to GDM.
A gnome-shell theme is actually just a CSS file (gnome-shell.css) plus other files (mostly images) referred to by gnome-shell.css.
In normal CSS we can use media queries to load different images on different screen sizes, etc. but media queries don't work in GnomeShell/GDM.
I don't know CSS except only a few very basic things and I don't know any other way to show different images on different screens/monitors or same image differently on different monitors.

It's not that I didn't research about it. I did research about this issue and that is how found out about media queries which work in web browsers but don't in GDM.

During that research, I found about some new CSS tags, properties, or whatever they are called in CSS that I could use for background images. So I added them to ;_set-gdm-theme_' script just to be safe.

Now, you can update gdm-tools to the latest commit and set your favorite theme again and check if it solves your problem.

If it doesn't, I would like you to tell me more about your problem. Exactly how is scale inappropriate? Is it zooming in a lot more than required? or is the image the appropriate size for one monitor but the other monitor needs the image to be upscaled, hence, causing the blur effect?

**Comment by realmazharhussain** [comment]
Personally, I have stopped using background images for GDM. The GDM themes I use don't look nice with any background image no matter how nice the background image is. Background images looked kinda good on older versions of GDM (like 3.30, etc) but It seems like developers are actively trying to make it so that using background image on GDM makes GDM look not-good.

I suppose a good gnome-shell theme, developed with GDM also as a target use case, may look good with a background image. But I don't think the developers of regularly maintained gnome-shell/GDM themes care about how their themes look in GDM with a background image. When they develop gnome-shell themes, I think they assume their themes are going to be used inside Gnome not GDM and they are not wrong to assume that. So, they care mostly only for how their theme looks in a Gnome session.

I am planning on adding the feature to use a color/gradient as GDM background instead of an image. Maybe that could be helpful to you.

**Comment by lonble** [comment]
Thanks for your reply. I have updated to the latest version, but it still doesn't work. I have two monitors, placed on the left and right, their resolutions are both 1920*1080. The resolution of my background image is also 1920*1080. The background image is enlarged to fill the two screens. I think its current resolution is 3840*2160. As a result, I cannot see the bottom half of the background image.

Just like this, The dashed line is my monitor, the Whole graph is the actual background image I guess:

```
+-------+-------+
|       |       |
+-------+-------+
:               :
.................
```

It’s really not a good idea to use a background image in GDM, I’m using the default image now.

**Comment by realmazharhussain** [comment]
Does GDM give a separate login screen on both the monitors or just 1 login screen spanned across both monitors.

I mean like this?
```
+----------------++----------------+
|      <>        ||      <>        |
|    ======      ||    ======      |
+----------------++----------------+
```
or this?
```
+----------------++----------------+
|               <||>               |
|       =========||=========       |
+----------------++----------------+
```

**Comment by lonble** [comment]
GDM only displays the login screen on the primary display

```
```

**Comment by realmazharhussain** [comment]
What about top bar?
Do both monitors have their own top bar?
or Single top bar is shown on both the monitors?
or Is the top bar present only on primary monitor?

**Comment by lonble** [comment]
The top bar present only on primary monitor.
Other monitors show nothing except the background picture.

**Comment by realmazharhussain** [comment]
I can't think of a fix to add in **_gdm-tools_** which would not mess up single monitor set ups But I could share some css code that would help with your problem on your specific setup.

### Steps:
1. upgrade gdm-tools (very important; don't ignore)
2. add following code to the end of /usr/share/themes/**\<theme-name\>**/gnome-shell/gnome-shell.css
```css
#lockDialogGroup {
    background-image: url('file:///usr/share/gnome-shell/theme/gdm-background.png');
    background-size: contain;
    background-position: top left;
    background-attachment: fixed;
    background-repeat: repeat;
}
```
3. Apply your favorite theme using `set-gdm-theme -s <theme-name> none`
4. Copy any 16:9 (aspect ratio) image file and paste it as /usr/share/gnome-shell/theme/gdm-background.png and it will look perfect (as in no unnecessary zooming and blur) on your setup
`sudo cp /path/to/image /usr/share/gnome-shell/theme/gdm-background.png`

**Note:** Replace **\<theme-name\>** with the actual name of the theme you want to apply

**Comment by lonble** [comment]
Thank you, this method is useful. But `background-position` doesn't seem to work. Repeating from the center causes the background image of each screen to be offset by 50%.

**Comment by realmazharhussain** [comment]
It didn't work for me either but image was not repeating from the center but from the right side which would have worked perfect But it seems your version of GDM is behaving differently from mine.

The only solution I see, now, is to create a new image of the resolution 3840x1080 by repeating your 1920x1080 image in an image editor.
