### ISSUE TITLE
Changing gdm theme makes the close button on the overview missing

### ISSUE THREAD

**Issue by Radical4ever** [realmazharhussain/gdm-tools#13]
hi, when i change the theme and log out and log in, the close button on the overview appears missing.

**Comment by realmazharhussain** [comment]
What theme are you using? And where did you get that theme?

**Comment by Radical4ever** [comment]
> What theme are you using? And where did you get that theme?

For gtk theme i use Graphite from vinceluice i got it from github, icons im using papirus (github too) but it happens on all icon theme.

**Comment by realmazharhussain** [comment]
Graphite (like many other Gnome Shell themes) is incomplete. That's why you are having such problems.

But don't worry. I will be adding an `--overlay-mode` option to `set-gdm-theme` command which will ensure that icons and other resources from default theme are added to the theme being applied if it does not already contain those resources.

For now, run the following commands to fix those issues

```bash
set-gdm-theme -x
themesDir=/usr/share/themes
scalableDir=gnome-shell/icons/scalable
for GraphiteDir in $themesDir/Graphite-*; do
  for resource in actions/preview-close-symbolic.svg status/eye-{not-looking,open-negative-filled}-symbolic.svg; do
    sudo install -Dm644 $themesDir/default-extracted/$scalableDir/$resource $GraphiteDir/$scalableDir/$resource
  done
done
set-gdm-theme -s -b
```

**Comment by realmazharhussain** [comment]
`overlayMode` has been added as a configuration option and its default value is `resources`.

It means **your problem has been solved**.

If you ever want to restore the previous behavior set overlayMode variable in `/etc/gdm-tools/set-gdm-theme.conf` to `none`.

**Comment by realmazharhussain** [comment]
Please! Update `gdm-tools` and Check if the fix works for you; And if it does, report back to me.

**Comment by Radical4ever** [comment]
Thanks!, now it works fine the close button is no longer missing and the show password button on gdm is no longer missing too. thanks for the help!!

**Comment by realmazharhussain** [comment]
You are welcome
