### ISSUE TITLE
Wallpaper setting not working on fedora

### ISSUE THREAD

**Issue by arun54321** [realmazharhussain/gdm-tools#14]
It doesn't change. Changing background color works.

`set-gdm-theme -s default /home/arun/Pictures/yosemite-tunnel-view-1920×1080.jpg`

**Comment by arun54321** [comment]
I tried using other [tool](https://copr.fedorainfracloud.org/coprs/zirix/gdm-wallpaper/). that works.

**Comment by realmazharhussain** [comment]
Thanks for reporting the issue

**Comment by realmazharhussain** [comment]
I think I have fixed the issue. Update to the latest version and check if it works now.

And don't forget to report back.
