### ISSUE TITLE
[BUG] cannot set gdm icon theme

### ISSUE THREAD

**Issue by OldWorldOrdr** [realmazharhussain/gdm-tools#17]
**Is your feature request related to a problem? Please describe.**
Its annoying that I can't set an icon theme for gdm.

**Describe the solution you'd like**
You should add a way to set the gdm icon theme.

**Comment by realmazharhussain** [comment]
Just run `gnomeconf2gdm` command. It will apply your current icon theme to GDM.

**Comment by OldWorldOrdr** [comment]
tried that, didnt work

**Comment by realmazharhussain** [comment]
This is a bug in `gdm-tools`. There is a similar bug reported in issue #12. I could not detect the source of that bug. It could be the same here.

**But** you can manually edit files in `/etc/dconf/db/gdm.d/' directory and if any file contains `icon-theme='theme-name'` line, delete the line and run `gnomeconf2gdm`. This may fix the problem.

**Comment by OldWorldOrdr** [comment]
@realmazharhussain the only file in `/etc/dconf/db/gdm.d/` is `99-gnomeconf2gdm`, which contains `icon-theme='Papirus'` (which is what i want it to be) but in gdm my icon theme appears to be `Pop` (the default in Pop_OS!)

**Comment by realmazharhussain** [comment]
Then it seems to be the exactly same problem as #12. For the moment, I cannot detect the cause of these problems.

**Comment by realmazharhussain** [comment]
The discussion on this problem should be continued in issue #12.
