### ISSUE TITLE
Any way to scale the login (greeter) screen to 2x with gdm-tools

### ISSUE THREAD

**Issue by Amondale** [realmazharhussain/gdm-tools#19]
### Description

Not sure if this should be a feature request, or I just missed something in the man pages. I have login screens that don't seem to respect the scaling set in the running gdm theme? Don't know if I'm saying this right, I'd like to scale the greeter screen 2x without doing it globally if possible.

**Comment by realmazharhussain** [comment]
No. There is no way to do it with gdm-tools. But you can do it manually. Just run the following commands in terminal

```bash
machinectl shell gdm@ /usr/bin/env gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
sudo cp -T ~/.config/monitors.xml ~gdm/.config/monitors.xml
sudo chown gdm: ~gdm/.config/monitors.xml
```

If you are on a Debian based system, replace the word `gdm` in above commands with `Debian-gdm`.

**Comment by Amondale** [comment]
@realmazharhussain Thank you for that tidbit! I found what looks like a slightly [simpler way to do this](https://askubuntu.com/questions/906797/scaling-gnome-login-screen-on-hidpi-display) but your way is a "one-liner" so pretty simple! Thanks again!
