### ISSUE TITLE
I am no longer able to set an image as a background

### ISSUE THREAD

**Issue by sisco70** [realmazharhussain/gdm-tools#2]
Hi,
The previous version worked fine with Ubuntu 20.04.2 LTS.
I have updated the script with the latest changes, but I am no longer able to set an image as a background.
I can only change the background color and theme.

I tried to reset with: 
`set-gdm-theme -r`
Without results..

I do:
`apt install --reinstall gnome-shell-common`
And reinstall everything again, but without solving anything..

Thank, you,
Francesco

**Comment by realmazharhussain** [comment]
Noted!

I'm gonna working on it as soon as possible.

**Comment by realmazharhussain** [comment]
### _Fixed!_

Update and try setting an image as GDM background again.
