### ISSUE TITLE
Showing wrong/unknown background.

### ISSUE THREAD

**Issue by ParaSpl01t** [realmazharhussain/gdm-tools#8]
The image I'm trying to set is a pure dark png but instead I get a blurry picture of something that looks like a mountain. I have no idea where that image came from.
```
[~] ➤ set-gdm-theme -l                                                       
default
ZorinPurple-Dark
[~] ➤ set-gdm-theme -s ZorinPurple-Dark /home/paradox/Pictures/wall-blank.png
cp: cannot create regular file '/usr/share/gnome-shell/theme/gdm-background': No such file or directory
Background set to image '/home/paradox/Pictures/wall-blank.png'
Theme set to 'ZorinPurple-Dark'
```

My system:
```
[~] ➤ paru -Q | grep gdm   
gdm 40.1-2
gdm-tools-git 66.15e1065-1
libgdm 40.1-2
[~] ➤ paru -Q | grep gnome-shell
gnome-shell 1:40.4-1
```

Sorry for the poor quality image. I couldn't figure out how to take screenshot in gdm.

![20210927_182327](https://user-images.githubusercontent.com/18276917/134912175-34b7016b-53de-470c-a612-4b0f4e398148.jpg)

**Comment by realmazharhussain** [comment]
I think I have fixed it. Update gdm-tools and try again. It should work now.

Let me know if it works or not.

**Comment by ParaSpl01t** [comment]
Sorry for the late reply.
I've updated gdm-tools and correct background image is shown.
Thank you

**Comment by realmazharhussain** [comment]
> Sorry for the late reply.

No need.

>  I've updated gdm-tools and correct background image is shown. Thank you.

You're welcome

>  Still got no idea about where the background in my attached photo is coming from.

I don't know for sure but it might be part of the theme you set i.e. ZorinPurple-Dark
