### ISSUE TITLE
Any way to switch icons?

### ISSUE THREAD

**Issue by sheeepdev** [realmazharhussain/gdm-tools#9]
I want to use different icons in GDM (for the battery, volume, and other icons) but I can't find a way to do it with your tool, is there a way to do this or can you add this functionality to your tool?

**Comment by realmazharhussain** [comment]
If you want to change GDM icon theme to be the same as you Gnome icon theme, just run the command `gnomeconf2gdm`. It will apply a lot of Gnome settings to GDM including icon/cursor theme.

If you want to change GDM icon theme to be something different than your Gnome icon theme, first make sure the file `/etc/dconf/profile/gdm` exists and has following as its content

```
user-db:user
system-db:gdm
file-db:/usr/share/gdm/greeter-dconf-defaults
```

if that file doesn't exist, create it and then create a file `/etc/dconf/db/gdm.d/99-z-icon-theme` with the following contents

```
[org/gnome/desktop/interface]
cursor-theme='xcursor-breeze-snow'
icon-theme='Adwaita'
```

and obviously, replace `xcursor-breeze-snow` with name of the theme you want to set as cursor theme and `Adwaita` with name of the theme you want to set as icon theme

In the end, run `sudo dconf update`

**Comment by sheeepdev** [comment]
Thanks, I need to check the documentation before saying anything, sorry
